{{- if .Values.misp.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tls-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: cloudflare-tls-secret
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: cloudflare-origin-cert
        # property: certificate
    - secretKey: tls.key 
      remoteRef:
        key: cloudflare-private-key
        # property: private-key

{{- end }}