apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: s3-secret       # name of the k8s Secret to be created
  data:
  - secretKey: s3.client.default.access_key
    remoteRef:
      key: initial-secret
      property: S3_SNAPSHOT_KEY

  - secretKey: s3.client.default.secret_key
    remoteRef:
      key: initial-secret
      property: S3_SNAPSHOT_SECRET
