apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alerts-webhook-01
spec:
  receivers:
    - name: discord-notifications
      webhookConfigs:
      - url: 'http://discord-alm.discord-alm.svc.cluster.local:9094'
    - name: null-notifications

  route:
    groupBy: [alertname]
    receiver: discord-notifications   # ✅ default ส่ง
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h

    routes:
    - matchers:
      - name: alertname
        matchType: =~
        value: 'KubeControllerManagerDown|KubeProxyDown|KubeSchedulerDown|NodeClockNotSynchronising|InfoInhibitor|TargetDown'
      receiver: null-notifications     # ❌ drop เฉพาะที่ไม่อยากได้
