apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zeekEth0.fullnameOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      containers:
        - name: zeek
          image: zeek/zeek:8.0.4
          imagePullPolicy: IfNotPresent

          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              export ZEEK_LOG_DIR=/usr/local/zeek/logs/current
              mkdir -p $ZEEK_LOG_DIR
              echo "Log dir = $ZEEK_LOG_DIR"
              zeek -i {{ .Values.zeekEth0.interfaceName }} -C local /etc/zeek/site/custom_logs.zeek &
              sleep 2
              ls -al $ZEEK_LOG_DIR
              tail -F $ZEEK_LOG_DIR/*.log

          resources:
            requests:
              cpu: {{ .Values.zeekEth0.resources.requests.cpu }}
              memory: {{ .Values.zeekEth0.resources.requests.memory }}
            limits:
              cpu: {{ .Values.zeekEth0.resources.limits.cpu }}
              memory: {{ .Values.zeekEth0.resources.limits.memory }}

          volumeMounts:
            - name: zeek-logs
              mountPath: /usr/local/zeek/logs
            - name: config-volume
              mountPath: /etc/zeek/site/custom_logs.zeek

      volumes:
        - name: zeek-logs
          emptyDir: {}

        - name: config-volume
          configMap:
            name: zeek-config
