apiVersion: v1
kind: ConfigMap
metadata:
  name: zeek-eth0-config
data:
  filebeat.yml: |
    filebeat.modules:
      - module: zeek
        connection:
          enabled: true
          var.paths: ["/zeek-logs/current/conn.log"]
        dns:
          enabled: true
          var.paths: ["/zeek-logs/current/dns.log"]
        http:
          enabled: true
          var.paths: ["/zeek-logs/current/http.log"]
        ssl:
          enabled: true
          var.paths: ["/zeek-logs/current/ssl.log"]

    #processors:
    #  - add_kubernetes_metadata: {}

    output.console:
      pretty: true
