domain: opencti.rtarf-censor.dev-hubs.com

### OpenCTI ###
opencti:
  enabled: true
  nameOverride: opencti

  replicaCount: 1
  env:
    ELASTICSEARCH__URL: https://opensearch-cluster-master:9200
    ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED: 'false'
    ELASTICSEARCH__USERNAME: 'admin'
    ELASTICSEARCH__PASSWORD: 'DuelHdboww0up;23'

    RABBITMQ__HOSTNAME: "opencti-main-rabbitmq"
    RABBITMQ__USERNAME: opencti
    RABBITMQ__PASSWORD: opencti
    REDIS__HOSTNAME: opencti-main-redis

  # --- Disable MinIO ---
  minio:
    enabled: false

  # --- Redis (internal) ---
  redis:
    enabled: true
    architecture: standalone

  # --- RabbitMQ (internal) ---
  rabbitmq:
    enabled: true
    auth:
      username: opencti
      password: opencti
    persistence:
      enabled: false

  opensearch:
    enabled: true
    plugins:
      - ingest-attachment

    extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: opencti-secret
            key: elasticsearch_password
      - name: OPENSEARCH_PLUGINS
        value: ingest-attachment

    persistence:
      enabled: true
      size: 20Gi
