domain: opencti.rtarf-censor.dev-hubs.com

### OpenCTI ###
opencti:
  enabled: true
  nameOverride: opencti

  replicaCount: 1
  env:
    ELASTICSEARCH__URL: https://opensearch-cluster-master:9200
    NODE_TLS_REJECT_UNAUTHORIZED: "0"

  # --- Disable MinIO ---
  minio:
    enabled: false

  # --- Redis (internal) ---
  redis:
    enabled: true
    architecture: standalone

  # --- RabbitMQ (internal) ---
  rabbitmq:
    enabled: true
    auth:
      username: opencti
      password: opencti
    persistence:
      enabled: false

  opensearch:
    enabled: true

    extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: opencti-secret
            key: elasticsearch_password

    persistence:
      enabled: true
      size: 20Gi
