apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: censor-arkime
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arkime/helm #อ้างตรงจาก repo arkime
    targetRevision: main
    path: 99-deployments/manifests/censor-arkime
    helm:
      valueFiles:
      - values.yaml
      - values-local.yaml
  destination:
    name: in-cluster
    namespace: censor-arkime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
